name: get_pong
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2flutter 

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  flutter_riverpod: ^2.0.0-dev.5
  glassmorphism: ^3.0.0
  protobuf: ^2.0.1
  grpc: ^3.0.2
  get_it: ^7.2.0
  date_time_format: ^2.0.1
      

dev_dependencies:      
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

