name: GetPong.Api Dev - Push to CR

on:
  push:
    branches:
      - dev
    paths:
      - "api/**"

env:
  REGISTRY: "getpong.azurecr.io"
  REGISTRY_USERNAME: "getpong"
  REPO: "getpong-api-dev"
  IMAGE: "getpong-dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ env.REGISTRY_USERNAME }} 
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ env.REGISTRY }}

      - name: Build and push container image to registry SHA
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}
          file: ./api/GetPong/Dockerfile          
          
      - name: Build and push container image to registry LATEST
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
          file: ./api/GetPong/Dockerfile
          
